### ISSUE TITLE
Tailwind CSS IntelliSense extension not working

### ISSUE THREAD

**Issue by cacauisadog** [dobicinaitis/tailwind-cli-extra#5]
Hello, everyone. I've been using this version of the standalone CLI in a Django project, and noticed that tailwind intellisense isn't working in VSCode, but it was back when I was using the regular `npm install` method. This is the error I repeatedly get in the Output tab of VSCode:

```
[tailwind.config.js] Initializing...
[tailwind.config.js] Failed to load workspace modules.
[tailwind.config.js] Using bundled version of `tailwindcss`: v3.4.1
[tailwind.config.js] Using bundled version of `postcss`: v8.4.31
[tailwind.config.js] Building...
[Error - 21:17:49] Tailwind CSS: Can't resolve 'daisyui' in '/Users/cauebc/Projects/ipersonal_django'
Error: Can't resolve 'daisyui' in '/Users/cauebc/Projects/ipersonal_django'
    at d (/Users/cauebc/.vscode/extensions/bradlc.vscode-tailwindcss-0.10.5/dist/tailwindServer.js:130:7139)
    at /Users/cauebc/.vscode/extensions/bradlc.vscode-tailwindcss-0.10.5/dist/tailwindServer.js:131:713
    at /Users/cauebc/.vscode/extensions/bradlc.vscode-tailwindcss-0.10.5/dist/tailwindServer.js:134:401
    at eval (eval at create (/Users/cauebc/.vscode/extensions/bradlc.vscode-tailwindcss-0.10.5/dist/tailwindServer.js:5:78), <anonymous>:15:1)
    at /Users/cauebc/.vscode/extensions/bradlc.vscode-tailwindcss-0.10.5/dist/tailwindServer.js:134:401
    at eval (eval at create (/Users/cauebc/.vscode/extensions/bradlc.vscode-tailwindcss-0.10.5/dist/tailwindServer.js:5:78), <anonymous>:16:1)
    at /Users/cauebc/.vscode/extensions/bradlc.vscode-tailwindcss-0.10.5/dist/tailwindServer.js:134:401
    at eval (eval at create (/Users/cauebc/.vscode/extensions/bradlc.vscode-tailwindcss-0.10.5/dist/tailwindServer.js:5:78), <anonymous>:15:1)
    at /Users/cauebc/.vscode/extensions/bradlc.vscode-tailwindcss-0.10.5/dist/tailwindServer.js:134:401
    at eval (eval at create (/Users/cauebc/.vscode/extensions/bradlc.vscode-tailwindcss-0.10.5/dist/tailwindServer.js:5:78), <anonymous>:15:1)
```

It can correctly find my `tailwind.config.js` file, but it looks like it's confused as to where the daisyui plugin is coming from. I'm running a Mac M2 Max, Sonoma 14.4.1 machine, and I've got the latest VSCode installed (as I type this), which is version 1.89.1. Any ideas? Is it even possible to make this work? If you need more info about my setup, I'd be glad to provide.

**Comment by dobicinaitis** [comment]
Hi! Unfortunately, the Tailwind CSS IntelliSense extension for VS Code doesn't function properly when non-native plugins are present in `tailwind.config.js`, but `node_modules` can't be located in the project directory. If you're willing to use `npm` to enable IntelliSense, you can check out [issue #3](https://github.com/dobicinaitis/tailwind-cli-extra/issues/3) for a workaround.
