### ISSUE TITLE
Support customizing existing themes

### ISSUE THREAD

**Issue by elfjes** [dobicinaitis/tailwind-cli-extra#6]
Current `tailwindcss-extra` works well when using builtin themes or creating custom themes. However, it does not support modifying builtin themes using the instructions in [How to customize an existing theme?](https://daisyui.com/docs/themes/#-7) because that source path (`daisyui/src/theming/themes`) is not included in the bundle and a `MODULE_NOT_FOUND` is thrown. Would it be possible to include it in the bundle?

**Comment by dobicinaitis** [comment]
Hi! I got it working. Give me a day or two, and I'll push the change and will create a new release.

**Comment by elfjes** [comment]
Awesome, that's great! looking forward to it :)

**Comment by dobicinaitis** [comment]
@elfjes, please check if the [latest binary](https://github.com/dobicinaitis/tailwind-cli-extra/releases/tag/v1.7.12) resolves the issue for you.

**Comment by elfjes** [comment]
@dobicinaitis perfect, thanks! 😁
