### ISSUE TITLE
Cant run this on my macOS(arm64) becuse its not siggned

### ISSUE THREAD

**Issue by moshe5745** [dobicinaitis/tailwind-cli-extra#9]
How can it be signed?

**Comment by dobicinaitis** [comment]
Hi, I don't have the hardware to verify this, so some debugging info would be appreciated. Check out [this](https://github.com/dobicinaitis/tailwind-cli-extra/discussions/4) discussion for commands that you can use to obtain the signature information. Additionally, please test whether the older [v1.2.1](https://github.com/dobicinaitis/tailwind-cli-extra/releases/tag/v1.2.1) version works for you.
